name: digital_clock
description: Digital clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2
  google_fonts: ^0.3.2
  flutter_svg: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: PressStart2P
      fonts:
        - asset: third_party/PressStart2P-Regular.ttf
  assets:
    - assets/windy.svg
    - assets/rainy.svg
    - assets/cloudy.svg
    - assets/fog.svg
    - assets/snow.svg
    - assets/sunny.svg
    - assets/thunder.svg